### ISSUE TITLE
Unhandled Promise

### ISSUE THREAD

**Issue by peterennis** [mlaanderson/database-js#1]
I have been looking at node-adodb and came across this project.
The use of promises is interesting.
I want to try with Access and Firebase.
How do I get started?

Testing the firebase example with RunKit.

Error:

![capture199](https://user-images.githubusercontent.com/140737/31324931-8711b3e8-ac6c-11e7-96de-abb5c2ee2315.png)

**Comment by mlaanderson** [comment]
If you're running it in RunKit, you have to specifically require database-js-firebase as well. RunKit won't auto-load the database driver.

See my RunKit example: https://runkit.com/mlaanderson/runkit-npm-database-js2
