### ISSUE TITLE
To adopt Semantic Versioning

### ISSUE THREAD

**Issue by thiagodp** [mlaanderson/database-js#10]
Please adopt [Semantic Versioning](https://semver.org/) in this project and in related projects. New versions could be released as [tags](https://git-scm.com/docs/git-tag).

**Comment by mlaanderson** [comment]
I tagged the current state at v1.2.2 to match the version on NPM. 

I have been using ``npm version`` which does tag the versions, but didn't understand git well enough to know how to push the tags up. I'll start on the semantic versioning from here.

**Comment by thiagodp** [comment]
Hi @mlaanderson. You can create a tag like this:
```shell
git tag v1.2.2 -m "Version description here"
```
Then push it to the remote repo:
```shell
git push --tags
```
To see all the current tags and their messages:
```shell
git tag -n
```
