### ISSUE TITLE
Add Travis build

### ISSUE THREAD

**Issue by thiagodp** [mlaanderson/database-js#12]
Activate this project in [Travis](https://travis-ci.org/), in order to let it check the build status. Then we can add an image of the build status to the `README.md` file.

@mlaanderson I've already added the file `.travis.yml` to the project.

**Comment by mlaanderson** [comment]
I ran a test build and it looks like there's problems with iojs and version 6. Node version 6 fails due to the async function in test.js, it should be an easy fix.

**Comment by thiagodp** [comment]
Fixed. Build status is now available at [README.md](https://github.com/mlaanderson/database-js).
