### ISSUE TITLE
Try to use the name "database-js" on NPM

### ISSUE THREAD

**Issue by thiagodp** [mlaanderson/database-js#13]
The original projected named 'database-js' is [abandoned](https://www.npmjs.com/package/database.js). Acessing its [project page](https://github.com/viatropos/database.js) returns a 404.

NPM has a [policy about disputes](https://www.npmjs.com/policies/disputes) that states `This process is an excellent way to: - Adopt an "abandoned" package (...)`, among other things. So, I think this is a good opportunity to get the name `database-js`.

**Comment by thiagodp** [comment]
@mlaanderson BTW, can you grant me access to *publish* (`npm publish`) in NPM? Last versions I had released were not published in NPM. Thanks!

**Comment by mlaanderson** [comment]
@thiagodp is your NPM user the same as on GitHub?

**Comment by thiagodp** [comment]
Yes

**Comment by mlaanderson** [comment]
You are now on the NPM project. I think that will give you publish.

**Comment by mlaanderson** [comment]
I have requested the database-js name on NPM, it looks like it can take a few weeks.

**Comment by thiagodp** [comment]
Nice

**Comment by thiagodp** [comment]
Thanks for adding me to NPM. I'll try to publish something soon.

**Comment by mlaanderson** [comment]
Done. It had to move to v3.0.0 to take over the package. Database-js2 is now supported by a branch for bug fixes.

**Comment by thiagodp** [comment]
Great

**Comment by thiagodp** [comment]
Couldn't you remove the existing versions from the old database-js?

E.g. `npm unpublish database-js@1.0.0` and so on

In this way, we could remove all the registered versions from the old package and then publish the ones from the new.

**Comment by mlaanderson** [comment]
Not according to the support team at NPM

**Comment by thiagodp** [comment]
Okay
