### ISSUE TITLE
Improve subprojects' keywords

### ISSUE THREAD

**Issue by thiagodp** [mlaanderson/database-js#19]
When trying to search `"database-js"` in [NPM](https://www.npmjs.com/search?q=database-js), the subprojects don't appear. Maybe adding the keyword `database-js` to them would make they do.

So, in order to improve the *discoverability* of database-js and subprojects, I suggest that:
- [x] Every subproject receive `database-js` as a keyword;
  - [x] [database-js-mysql](https://github.com/mlaanderson/database-js-mysql)
  - [x] [database-js-postgres](https://github.com/mlaanderson/database-js-postgres)
  - [x] [database-js-sqlite](https://github.com/mlaanderson/database-js-sqlite)
  - [x] [database-js-adodb](https://github.com/mlaanderson/database-js-adodb)
  - [x] [database-js-firebase](https://github.com/mlaanderson/database-js-firebase)
  - [x] [database-js-ini](https://github.com/mlaanderson/database-js-ini)
  - [x] [database-js-xlsx](https://github.com/mlaanderson/database-js-xlsx)
  - [x] [database-js-csv](https://github.com/mlaanderson/database-js-csv)
  - [X] [database-js-json](https://github.com/thiagodp/database-js-json)
- [x] Database-js receive subprojects' names as keywords (e.g. `database-js-mysql`, etc.). **DONE**

NPM uses the keywords from `package.json`.

**Comment by mlaanderson** [comment]
All the current subprojects have database-js as a keyword.
