### ISSUE TITLE
Add support to MS SQL Server for Linux and Mac

### ISSUE THREAD

**Issue by thiagodp** [mlaanderson/database-js#20]
I'm currently building a version [here](https://github.com/thiagodp/database-js-mssql), but I couldn't test it yet. I'll try to release it ASAP.

**Comment by mlaanderson** [comment]
I'll try to install MS SQL Server to test it. Right now my machine can't reach packages.microsoft.com to install the Ubuntu version of SQL Server

**Comment by thiagodp** [comment]
Hi @mlaanderson, I just did a simple test on Ubuntu following [these installation procedures](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-linux-2017). It worked for queries and insert/update/delete with transactions. If you can, please check it too. Thx!
