### ISSUE TITLE
Add support to EMACS platform

### ISSUE THREAD

**Issue by proxy-m** [mlaanderson/database-js#27]
:-)

**Comment by thiagodp** [comment]
Hello @proxy-m, what is needed to do that? 

PRs are welcomed. :)

**Comment by proxy-m** [comment]
Hi! You can start from here :-)

https://common-lisp.net/project/parenscript/
https://github.com/jscl-project/jscl
http://lisperator.net/slip/impl
https://github.com/emacs-mirror/emacs
https://github.com/emscripten-core/emscripten
https://github.com/fabiosperotto/linuxJS
https://github.com/killinux/jslinux-bellard
https://github.com/copy/v86

Good luck!

**Comment by thiagodp** [comment]
This project does not need Emacs support. If you desire it, so please submit a PR.
