### ISSUE TITLE
Add support to JDBC connection

### ISSUE THREAD

**Issue by proxy-m** [mlaanderson/database-js#28]
With help of compiled by JSweet partial OpenJDK code of JDBC.

**Comment by thiagodp** [comment]
Hello @proxy-m, IMO, this is out of the project's scope. Database-js does not aim to be a JavaScript version of JDBC. Changing its architecture would affect all the current drivers.

**Comment by proxy-m** [comment]
Or you can wrap Database-JS api around minimal JRE+JDBC runtime

(e.g. around JRE 6 or 8 from OpenJDK or TeaVM).

So, you will support every DB, which has JDBC driver realization.
