### ISSUE TITLE
Beter examples

### ISSUE THREAD

**Issue by vladano** [mlaanderson/database-js#29]
Please,
Can you provide better examples, how to use database-js?
Something like this https://www.w3schools.com/nodejs/nodejs_mysql_create_db.asp
How to create database, create table, insert into table a single row and insert multiple rows from array, update data, delete data ...
database-je nice because support a lot of different drivers.

Thanks in advance,
VladanO

**Comment by thiagodp** [comment]
Hi @vladano, more examples and a basic API description were added to [README.md](https://github.com/mlaanderson/database-js).

You may find more examples at the page of your preferred [database driver](https://github.com/mlaanderson/database-js#drivers).

I'm closing this Issue for now.  Please feel free to give more suggestions.
