### ISSUE TITLE
hang await statement.query always loading

### ISSUE THREAD

**Issue by tegarkurniawan** [mlaanderson/database-js#30]
conn = new Connection("database-js-postgres://postgres:password@ip:5432/db"); 
            try {
                statement = await conn.prepareStatement("SELECT * FROM connection WHERE name = ?");
                rows = await statement.query('datasama');
                console.log(rows);
            } catch (error) {
                console.log(error);
            } finally {
                await connection.close();
            }

**Comment by thiagodp** [comment]
Hello, @tegarkurniawan!
Is the problem occurring only with the driver for Postgres ?
If so, I would suggest you to close this Issue and open a new one at [the driver page](https://github.com/mlaanderson/database-js-postgres). Thx!

**Comment by thiagodp** [comment]
I'm closing this Issue for now, since it's possibly a driver-specific Issue.
