### ISSUE TITLE
Accept connection parameters from a plain object

### ISSUE THREAD

**Issue by thiagodp** [mlaanderson/database-js#4]
Currently, `Connection` currently receives a `connectionString`:
```javascript
class Connection {
    constructor(connectionString, driver) {
        this.__base = ParseConnection(connectionString, driver);
        . . .
    }
  . . .
}
```
Sometimes it is desirable to create a connection passing parameters, such as in `ConnectionObject`, or maybe using a plain object.

So, to adjusting `Connection`'s constructor to accept both a string or a `ConnectionObject` would be:
```javascript
class Connection {
    constructor(conn, driver) {
        this.__base = 'string' === typeof conn ? ParseConnection(conn, driver) : conn;
        . . .
   }
   . . .
}
```
To receiving a plain object with connection properties, I think it would be better changing `ConnectionObject` instead of `Connection`. In this case, `ConnectionObject` could have a static constructor-like method:

```javascript
class ConnectionObject {
   ...
   static fromPlain( obj, driver ) {
      return new ConnectionObject(
        obj[ 'driverName' ], 
        obj[ 'username' ],
        obj[ 'password' ],
        obj[ 'hostname' ],
        obj[ 'port' ],
        obj[ 'database' ],
        obj[ 'parameters' ],
        driver
      );
   }
  . . .
}
```
And then we could create a connection from a plain object:
```javascript
let p = require( 'mydb.json' ); // a JSON file with database connection properties
let c = new Connection( ConnectionObject.fromPlain( p, driver ), driver );
// or just
let c = new Connection( ConnectionObject.fromPlain( require( 'mydb.json' ), driver ) );
```

Wouldn't it be nice?

**Comment by thiagodp** [comment]
@mlaanderson , I've added a [Pull Request](https://github.com/mlaanderson/database-js/pull/7).

**Comment by mlaanderson** [comment]
@thiagodp , those changes look good. Thanks.

I'm not a software developer, I'm a hardware engineer, but I needed a flexible tool for my test lab. Bear with me as I figure git and versioning out.

**Comment by mlaanderson** [comment]
Since you got it working, I'm going to close this issue.

**Comment by thiagodp** [comment]
>I'm not a software developer, I'm a hardware engineer, but I needed a flexible tool for my test lab. Bear with me as I figure git and versioning out.

@mlaanderson Hey, you're doing a great job with `database-js`! Many thanks!
