### ISSUE TITLE
Add support to JSON files

### ISSUE THREAD

**Issue by thiagodp** [mlaanderson/database-js#5]
Maybe in a project named `database-js-json`

**Comment by mlaanderson** [comment]
That project could be based on the Firebase one.

**Comment by thiagodp** [comment]
Maybe [js-sql](https://github.com/avz/jl-sql) could be used underneath.

**Comment by thiagodp** [comment]
I've just implemented [database-js-json](https://github.com/thiagodp/database-js-json) over the [jl-sql-api](https://github.com/avz/node-jl-sql-api).
