### ISSUE TITLE
Simpler driver names

### ISSUE THREAD

**Issue by thiagodp** [mlaanderson/database-js#8]
Instead of using `database-js-driver://`, the project could adopt just `driver://`.

Examples (JDBC-like):
- `mysql` for MySQL databases (currently `database-js-mysql`)
- `postgresql` for PostgreSQL databases (currently `database-js-postgres`)
- `sqlite` for SQLite databases (currently `database-js-sqlite`)
- `firebase` for Firebase databases (currently `database-js-firebase`)
- `ado` for ActiveX Data Objects, like MS Excel tables and MS Access databases (currently `database-js-adodb`)
- `ini` for INI files (currently `database-js-ini`)

Other examples (for future use?):
- `json` for JSON files
- `xml` for XML files
- `odbc` for ODBC access to databases
- `oracle` for Oracle databases
- `sqlserver` for MS SQL Server databases
- `firebirdsql` for Firebird databases
- `mariadb` for MariaDB (as an alternative driver to MySQL)

**Comment by mlaanderson** [comment]
With the current implementation, the driver is loaded with a require. Since there were several packages with those names, I opted to use the longer names.

We could use a scheme like:
````
function loadModule(driver_name) {
    try {
        require.resolve(driver_name);
        return require(driver_name);
    } catch (e) {
       return false;
    }
}

driver = loadModule('database-js-' + driver_name) || loadModule('jsdbc-' + driver_name) || require(driver_name);
````
That would allow database-js-* drivers to be loaded by their simple name.

**Comment by mlaanderson** [comment]
Added in 8512ad58171c1b0a30ef0870ea3690d8dd7f631b, and tagged in [v1.3.1](https://github.com/mlaanderson/database-js/releases/tag/v1.3.1)

Simple names (e.g. postgres, mysql) will now resolve to database-js-simplename or jsdbc-simplename.
