### ISSUE TITLE
Update project to include database-js-ini

### ISSUE THREAD

**Issue by thiagodp** [mlaanderson/database-js#9]
If [database-js-ini](https://github.com/mlaanderson/database-js-ini) is stable enough, `database-js` could be updated to include it. 

E.g.: update `README.md` and `package.json`

**Comment by mlaanderson** [comment]
database-js-ini is now included in the readme/wiki. package.json doesn't reference any of the drivers as dependencies, but does as devDependencies, including database-js-ini.
